apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: mysql
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  type: mysql
  topologies:
    - name: server
      components:
        - name: server
          compDef: {{ include "mysql.componentDefName" . }}
      default: true
    - name: with-proxy
      components:
        - name: server
          compDef: {{ include "mysql.componentDefName" . }}
        - name: proxysql
          compDef: {{ include "proxysql.componentDefName" . }}
      orders:
        startupOrder: # The server will start before the proxy is created.
          - server
          - proxysql
        shutdownOrder: # The proxy will be shut down (destroyed) before the server.
          - proxysql
          - server
        updateOrder: # When there are multiple component update operations, follow the order specified here.
          - server
          - proxysql
    - name: ref-orchestrator
      components:
        - name: server
          compDef: {{ include "mysql.componentDefName" . }}-orc
    - name: ref-orchestrator-with-proxy
      components:
        - name: server
          compDef: {{ include "mysql.componentDefName" . }}-orc
        - name: proxysql
          compDef: {{ include "proxysql.componentDefName" . }}-orc
      orders:
        startupOrder: # The server will start before the proxy is created.
          - server
          - proxysql
        shutdownOrder: # The proxy will be shut down (destroyed) before the server.
          - proxysql
          - server
        updateOrder: # When there are multiple component update operations, follow the order specified here.
          - server
          - proxysql